name: Build

on: [workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: macos-12
    env:
      ATOM_DEV_RESOURCE_PATH: ${{ github.workspace }}
      ATOM_ELECTRON_URL: https://artifacts.electronjs.org/headers/dist
    steps:
      - uses: actions/checkout@v3
        with:
          repository: atom/atom
          ref: v1.63.1
      - run: |
          brew update
          brew install python@3.8
      - run: echo "$(brew --prefix)/opt/python@3.8/libexec/bin" >> $GITHUB_PATH
      - uses: actions/setup-node@v3
        with:
          node-version: "12.14.1"
          cache: "npm"
      - run: npm i -g npm@6.14.13
      - run: script/bootstrap
      - run: script/build --compress-artifacts --no-bootstrap
      - uses: actions/upload-artifact@v4
        with:
          name: atom-mac
          path: out/atom-mac.zip
          retention-days: 1
